<script setup lang="ts">
import { navBack } from '@/composables/useNavBar'
import { ref } from 'vue'; import { submitFeedback, type FeedbackCategory } from '../../api/feedback'
definePage({name:'feedback',layout:'default',style:{navigationStyle:'custom',navigationBarTitleText:'反馈建议'}})
const categories:FeedbackCategory[]=['功能建议','体验问题','内容反馈','其他'];const category=ref<FeedbackCategory>('功能建议');const content=ref('');const contact=ref('');const sending=ref(false)
async function submit(){if(!content.value.trim())return uni.showToast({title:'写下你的建议吧',icon:'none'});sending.value=true;try{await submitFeedback({category:category.value,content:content.value.trim(),contact:contact.value.trim()||undefined});content.value='';contact.value='';uni.showToast({title:'锅仔收到啦，谢谢你',icon:'success'})}catch(e:any){uni.showToast({title:e.message||'提交失败',icon:'none'})}finally{sending.value=false}}
</script>
<template><view class="feedback-page"><wd-navbar title="反馈建议" left-arrow safe-area-inset-top @click-left="navBack" /><view class="feedback-hero"><view><text class="feedback-kicker">GUOZAI IS LISTENING</text><text class="feedback-title">你的每一句话，<br/>锅仔都会认真听。</text></view><image src="/static/guozai/action_08_peek.png" mode="aspectFit"/></view><view class="feedback-card"><text class="label">这次想说什么？</text><view class="chips"><text v-for="i in categories" :key="i" :class="['chip',{active:category===i}]" @click="category=i">{{i}}</text></view><text class="label">具体说说吧</text><textarea v-model="content" maxlength="1000" placeholder="例如：希望时光机可以按月份筛选…"/><text class="count">{{content.length}}/1000</text><text class="label">联系方式（可选）</text><input v-model="contact" maxlength="100" placeholder="方便时留下微信号或邮箱"/><view :class="['submit',{disabled:sending}]" @click="submit">{{sending?'正在送给锅仔…':'提交建议'}}</view></view></view></template>
<style lang="scss" scoped>.feedback-page{min-height:100vh;padding:0 32rpx;background:var(--mrc-bg);box-sizing:border-box}.feedback-hero{display:flex;justify-content:space-between;align-items:center;margin:12rpx 0 24rpx;padding:32rpx;border:2rpx solid var(--mrc-border);border-radius:34rpx;background:var(--mrc-surface-peach)}.feedback-hero image{width:160rpx;height:160rpx}.feedback-kicker{display:block;color:var(--mrc-accent);font-size:19rpx;font-weight:800;letter-spacing:2rpx}.feedback-title{display:block;margin-top:12rpx;color:var(--mrc-text-deep);font-size:36rpx;font-weight:800;line-height:1.4}.feedback-card{padding:28rpx;border-radius:30rpx;background:var(--mrc-surface);border:2rpx solid var(--mrc-border-light)}.label{display:block;margin:0 0 14rpx;color:var(--mrc-text-deep);font-size:28rpx;font-weight:700}.chips{display:flex;flex-wrap:wrap;gap:12rpx;margin-bottom:28rpx}.chip{padding:13rpx 20rpx;border-radius:28rpx;background:var(--mrc-bg);color:var(--mrc-text-sub);font-size:24rpx}.chip.active{background:var(--mrc-accent-soft);color:var(--mrc-accent);font-weight:700}textarea,input{width:100%;box-sizing:border-box;padding:20rpx;border:2rpx solid var(--mrc-border-light);border-radius:20rpx;background:var(--mrc-bg);font-size:26rpx;color:var(--mrc-text-deep)}textarea{height:220rpx}.count{display:block;margin:8rpx 0 24rpx;text-align:right;color:var(--mrc-text-light);font-size:21rpx}.submit{margin-top:30rpx;padding:28rpx;border-radius:50rpx;text-align:center;background:var(--mrc-primary-grad);color:#fff;font-size:30rpx;font-weight:800}.disabled{opacity:.6}</style>
