/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by vite-plugin-uni-pages

type _LocationUrl =
  "/pages/index/index" |
  "/pages/about/index" |
  "/pages/album/index" |
  "/pages/calendar/index" |
  "/pages/feedback/index" |
  "/pages/gallery/index" |
  "/pages/mood/index" |
  "/pages/preferences/index" |
  "/pages/privacy/index" |
  "/pages/profile/index" |
  "/pages/recipe/index" |
  "/pages/record/index" |
  "/pages/report/index" |
  "/pages/settings/index" |
  "/pages/timeline/index";

interface NavigateToOptions {
  url: _LocationUrl;
}
interface RedirectToOptions extends NavigateToOptions {}

interface SwitchTabOptions {
  url: "/pages/index/index" | "/pages/record/index" | "/pages/profile/index"
}

type ReLaunchOptions = NavigateToOptions | SwitchTabOptions;

declare interface Uni {
  navigateTo(options: UniNamespace.NavigateToOptions & NavigateToOptions): void;
  redirectTo(options: UniNamespace.RedirectToOptions & RedirectToOptions): void;
  switchTab(options: UniNamespace.SwitchTabOptions & SwitchTabOptions): void;
  reLaunch(options: UniNamespace.ReLaunchOptions & ReLaunchOptions): void;
}

declare module "virtual:uni-pages" {
  export type LocationUrl = _LocationUrl;
}
