/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by vite-plugin-uni-pages

type _LocationUrl =
  "/pages/index/index" |
  "/pages/about/index" |
  "/pages/album/index" |
  "/pages/calendar/index" |
  "/pages/feedback/index" |
  "/pages/gallery/index" |
  "/pages/mood/index" |
  "/pages/profile/index" |
  "/pages/recipe/index" |
  "/pages/record/index" |
  "/pages/report/index" |
  "/pages/timeline/index" |
  "/subPages/ci/index" |
  "/subPages/create-uni/index" |
  "/subPages/feedback/index" |
  "/subPages/icon/index" |
  "/subPages/pinia/index" |
  "/subPages/request/index" |
  "/subPages/router/demo-aftereach" |
  "/subPages/router/demo-guard" |
  "/subPages/router/demo-object" |
  "/subPages/router/demo-params" |
  "/subPages/router/demo-protected" |
  "/subPages/router/demo-query" |
  "/subPages/router/demo-string" |
  "/subPages/router/index" |
  "/subPages/skills/index" |
  "/subPages/styles/index" |
  "/subPages/uni-ku-root/index" |
  "/subEcharts/echarts/index" |
  "/subAsyncEcharts/asyncEcharts/index";

interface NavigateToOptions {
  url: _LocationUrl;
}
interface RedirectToOptions extends NavigateToOptions {}

interface SwitchTabOptions {
  url: "/pages/index/index" | "/pages/record/index" | "/pages/profile/index"
}

type ReLaunchOptions = NavigateToOptions | SwitchTabOptions;

declare interface Uni {
  navigateTo(options: UniNamespace.NavigateToOptions & NavigateToOptions): void;
  redirectTo(options: UniNamespace.RedirectToOptions & RedirectToOptions): void;
  switchTab(options: UniNamespace.SwitchTabOptions & SwitchTabOptions): void;
  reLaunch(options: UniNamespace.ReLaunchOptions & ReLaunchOptions): void;
}

declare module "virtual:uni-pages" {
  export type LocationUrl = _LocationUrl;
}
