/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by vite-plugin-uni-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    CommonDesignSheet: typeof import('./components/common/DesignSheet.vue')['default']
    CommonIcon: typeof import('./components/common/Icon.vue')['default']
    CommonStatRow: typeof import('./components/common/StatRow.vue')['default']
    DemoBlock: typeof import('./components/DemoBlock.vue')['default']
    GlobalDialog: typeof import('./components/GlobalDialog.vue')['default']
    GlobalLoading: typeof import('./components/GlobalLoading.vue')['default']
    GlobalToast: typeof import('./components/GlobalToast.vue')['default']
    GuozaiEmptyState: typeof import('./components/guozai/EmptyState.vue')['default']
    GuozaiErrorState: typeof import('./components/guozai/ErrorState.vue')['default']
    GuozaiGuozai: typeof import('./components/guozai/Guozai.vue')['default']
    GuozaiGuozaiImage: typeof import('./components/guozai/GuozaiImage.vue')['default']
    GuozaiLoadingGuozai: typeof import('./components/guozai/LoadingGuozai.vue')['default']
    GuozaiLoadingState: typeof import('./components/guozai/LoadingState.vue')['default']
    GuozaiMoodPicker: typeof import('./components/guozai/MoodPicker.vue')['default']
    GuozaiSuccessModal: typeof import('./components/guozai/SuccessModal.vue')['default']
    MoodMoodGrid: typeof import('./components/mood/MoodGrid.vue')['default']
    PrivacyPopup: typeof import('./components/PrivacyPopup.vue')['default']
    RecipeRecipeCard: typeof import('./components/recipe/RecipeCard.vue')['default']
    WdConfigProvider: typeof import('@wot-ui/ui/components/wd-config-provider/wd-config-provider.vue')['default']
    WdGap: typeof import('@wot-ui/ui/components/wd-gap/wd-gap.vue')['default']
    WdNavbar: typeof import('@wot-ui/ui/components/wd-navbar/wd-navbar.vue')['default']
    WdSwitch: typeof import('@wot-ui/ui/components/wd-switch/wd-switch.vue')['default']
    WdTabbar: typeof import('@wot-ui/ui/components/wd-tabbar/wd-tabbar.vue')['default']
    WdTabbarItem: typeof import('@wot-ui/ui/components/wd-tabbar-item/wd-tabbar-item.vue')['default']
  }
}
